FROM node:20.15.1-alpine

WORKDIR /usr/src/app

COPY ../package.json ../package-lock.json ../turbo.json ./

COPY ../apps/user-app ./apps/user-app
COPY ../packages ./packages

RUN npm install
RUN npm run db:generate
RUN npm run build

ENV DATABASE_URL="" NEXTAUTH_URL="" NEXTAUTH_SECRET=""

CMD [ "npm" , "run" , "start-user-app" ]