name: Build-Push Image and Deploy to AWS

on:
  push:
    branches:
      - main
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Login to dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build user app Image and Push to Dockerhub
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/Dockerfile.user
          push: true
          tags: rahulsrvastva/wizzer-user-app:latest

      - name: Build webhook Image and Push to Dockerhub
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/Dockerfile.webhook
          push: true
          tags: rahulsrvastva/wizzer-webhook-app:latest

      - name: Verify Pushed user-app Image
        run: docker pull rahulsrvastva/wizzer-user-app:latest

      - name: Verify Pushed webhook-app Image
        run: docker pull rahulsrvastva/wizzer-webhook-app:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PASSKEY }}
          script: |
            sudo docker pull rahulsrvastva/wizzer-user-app:latest
            sudo docker pull rahulsrvastva/wizzer-webhook-app:latest
            sudo docker stop user-app || true
            sudo docker rm user-app || true
            sudo docker stop webhook-app || true
            sudo docker rm webhook-app || true
            sudo docker run -d -p 3000:3000 --name user-app -e DATABASE_URL=${{ secrets.DATABASE_URL }} -e NEXTAUTH_URL=${{ vars.NEXTAUTH_URL }} -e NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }} rahulsrvastva/wizzer-user-app:latest
            sudo docker run -d -p 3002:3002 --name webhook-app -e DATABASE_URL=${{ secrets.DATABASE_URL }} rahulsrvastva/wizzer-webhook-app:latest